
import { AlertCircle, ArrowRight, Route, ShieldAlert, MapPin } from "lucide-react";
const nav=[{label:"Live Impact",href:"/"},{label:"Route Checks",href:"/route-checks"},{label:"Road Blocks",href:"/road-blocks"}];
export default function Block(){return <div className="min-h-screen bg-slate-100 text-slate-950">
<header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-[1440px] items-center justify-between px-6 py-4"><div className="flex items-center gap-3"><ShieldAlert className="h-7 w-7 text-blue-700"/><div><h1 className="text-xl font-bold">RouteResilience</h1><p className="text-xs text-slate-500">Chelsea / Battersea</p></div></div><nav className="flex gap-1 rounded-lg bg-slate-100 p-1">{nav.map(x=><a key={x.label} href={x.href} className={x.href==="/route-checks"?"rounded-md bg-white px-3 py-2 text-sm font-semibold text-blue-700 shadow-sm":"rounded-md px-3 py-2 text-sm text-slate-600"}>{x.label}</a>)}</nav></div></header>
<main className="mx-auto max-w-[1440px] space-y-4 px-6 py-5">
<div><p className="text-xs font-bold uppercase tracking-[0.18em] text-slate-500">Operational routing</p><h2 className="text-2xl font-bold">Route Checks</h2></div>
<section className="rounded-lg border border-slate-200 bg-white p-4 shadow-sm"><div className="grid grid-cols-[1fr_36px_1fr_140px_170px] items-end gap-3"><label className="text-xs font-semibold text-slate-600">FROM<select disabled className="mt-2 h-11 w-full rounded-md border bg-slate-50 px-3 text-sm text-slate-400"><option>Connect Locations table</option></select></label><ArrowRight className="mb-3 h-5 w-5 text-slate-400"/><label className="text-xs font-semibold text-slate-600">TO<select disabled className="mt-2 h-11 w-full rounded-md border bg-slate-50 px-3 text-sm text-slate-400"><option>Connect Locations table</option></select></label><label className="text-xs font-semibold text-slate-600">PROFILE<div className="mt-2 flex h-11 items-center rounded-md border bg-slate-50 px-3 text-sm font-medium">driving-car</div></label><button disabled className="h-11 rounded-md bg-blue-700 px-5 text-sm font-bold text-white opacity-50">CHECK ROUTE</button></div><p className="mt-3 flex items-center gap-2 text-xs text-amber-700"><AlertCircle className="h-4 w-4"/>The existing Check route workflow is not available in this workspace yet.</p></section>
<section className="grid grid-cols-[1fr_1fr_1.2fr] gap-3"><div className="rounded-lg border bg-white p-4"><p className="text-xs font-bold uppercase text-slate-500">Normal</p><p className="mt-3 text-2xl font-bold">— min</p><p className="text-sm text-slate-500">— km</p></div><div className="rounded-lg border bg-white p-4"><p className="text-xs font-bold uppercase text-slate-500">With active disruptions</p><p className="mt-3 text-2xl font-bold text-blue-700">— min</p><p className="text-sm text-slate-500">— km</p></div><div className="rounded-lg bg-blue-700 p-4 text-white"><p className="text-xs font-bold uppercase text-blue-100">Impact</p><p className="mt-1 text-4xl font-black">— MIN</p><p className="text-sm text-blue-100">— km additional distance</p></div></section>
<section className="overflow-hidden rounded-lg border bg-white shadow-sm"><div className="flex items-center justify-between border-b px-4 py-3"><div><h3 className="font-bold">Route map</h3><p className="text-xs text-slate-500">Normal route, disruption route and active blocks</p></div><div className="flex gap-4 text-xs"><span>-- Normal</span><span className="text-blue-700">━ Disruption</span><span className="text-red-700">■ Blocked</span></div></div><div className="relative flex h-[480px] items-center justify-center overflow-hidden bg-slate-200" style={{backgroundImage:"linear-gradient(rgba(148,163,184,.18) 1px, transparent 1px),linear-gradient(90deg,rgba(148,163,184,.18) 1px,transparent 1px)",backgroundSize:"32px 32px"}}><div className="absolute inset-x-0 top-1/2 h-24 -rotate-3 bg-blue-100/80"></div><div className="relative rounded-lg border bg-white/90 px-6 py-5 text-center shadow-sm"><MapPin className="mx-auto h-7 w-7 text-blue-700"/><p className="mt-2 text-sm font-semibold">Route geometry ready for data wiring</p><p className="mt-1 text-xs text-slate-500">Leaflet / OpenStreetMap presentation area</p></div></div></section>
<section className="rounded-lg border bg-white p-5"><h3 className="font-bold">Operational Assessment</h3><p className="mt-3 text-sm text-slate-500">The stored Claude Assessment from the latest Route Check will appear here.</p></section>
<section className="overflow-hidden rounded-lg border bg-white"><div className="border-b px-4 py-3"><h3 className="font-bold">Previous route checks</h3><p className="text-xs text-slate-500">Newest first</p></div><div className="grid grid-cols-8 gap-3 border-b bg-slate-50 px-4 py-2 text-[11px] font-bold uppercase text-slate-500">{["Name","From","To","Normal","Detour","Extra","Reachable","Checked at"].map(x=><span key={x}>{x}</span>)}</div><div className="flex h-24 items-center justify-center text-sm text-slate-500"><Route className="mr-2 h-4 w-4"/>No connected Route Checks records</div></section>
</main></div>}
